FORMAT: 1A

# World View
An API for the worldview project. For more info check the README.md in the root directory.

## Nearest Locations [/nearest]
### List Photos from nearest Locations [GET]
+ Response 200 (application/json)

        [{
            "id": 1, 
            "location": "Sofia, Bulgaria",
            "season": "spring",
            "imgurl": "http://d1vmp8zzttzftq.cloudfront.net/wp-content/uploads/2012/05/national-palace-of-culture-also-called-sofia-bulgaria-1600x1062.jpg",
            "description": "National Palace of Culture",
            "author": "John Doe"
        }, 
        {
            "id": 2, 
            "location": "Sofia, Bulgaria",
            "season": "autumn",
            "imgurl": "http://upload.wikimedia.org/wikipedia/commons/b/b7/Adlerbr%C3%BCcke_Sofia_c_014.JPG",
            "description": "Eagles' Bridge",
            "author": "John Doe"
        },
        {
            "id": 3, 
            "location": "Sofia, Bulgaria",
            "season": "spring",
            "imgurl": "http://www.sofia-guide.com/assets/love_bridge_main.jpg",
            "description": "Lovers' Bridge",
            "author": "John Doe"
        }]

## Search for Photos [/search]
Listing all photos which fit with the given description (City and/or Season).

### List all photos that fit your requirements [GET]
+ Response 200 (application/json)

    + Body
    
            [{
                "id": 1, 
                "location": "Sofia, Bulgaria",
                "season": "spring",
                "imgurl": "http://d1vmp8zzttzftq.cloudfront.net/wp-content/uploads/2012/05/national-palace-of-culture-also-called-sofia-bulgaria-1600x1062.jpg",
                "description": "National Palace of Culture",
                "author": "John Doe"
            },
            {
                "id": 5, 
                "location": "Madrid, Spain",
                "season": "autumn",
                "imgurl": "http://picturetouring.com/wp-content/uploads/Estatua-Felipe-IV-Oriente-palacio-copia.jpg",
                "description": "Monument to Philip IV",
                "author": "John Doe"
            }]


## Single Photo [/photos/{id}]

### View a photo [GET]

+ Response 200 (application/json)
    +   body    
    
            [{
                "id": 1, 
                "location": "Sofia, Bulgaria",
                "season": "spring",
                "imgurl": "http://d1vmp8zzttzftq.cloudfront.net/wp-content/uploads/2012/05/national-palace-of-culture-also-called-sofia-bulgaria-1600x1062.jpg",
                "description": "National Palace of Culture",
                "author": "John Doe"
            }]

### Upload a Photo [POST]
+ Request (application/json)

            [{
                "location": "Bali, Indonesia",
                "season": "summer",
                "imgurl": "https://turismoadaptado.files.wordpress.com/2013/08/bedugul-is-a-mountain-lake-resort-area-in-bali-indonesia-located-in-the-centre-north-region-of-the-island.jpg",
                "description": "Bedugul"
            }]

+ Response 201 (application/json)

            [{
                "id": 6, 
                "location": "Bali, Indonesia",
                "season": "summer",
                "imgurl": "https://turismoadaptado.files.wordpress.com/2013/08/bedugul-is-a-mountain-lake-resort-area-in-bali-indonesia-located-in-the-centre-north-region-of-the-island.jpg",
                "description": "Bedugul",
                "author": "John Doe"
            }]
            
### Delete a photo [DELETE]
+ Response 204
            

## Users [/users]
### Add an user [POST]
+ Request (application/json)

            {
                "name": "John",
                "username": "johndoexx",
                "password": "secret",
                "email": "johndoe@email.com"
            }

+ Response 201 (application/json)

        
            [{
                "id": 1, 
                "name": "John",
                "username": "johndoexx",
                "password": "secret",
                "email": "johndoe@email.com"
            }]


## Single User info [/users/{id}]
Viewing or removing users...

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the users to perform action with. Has example value.

### Get single user info [GET]
+ Response 200 (application/json)

    + Body
    
            [{
                "id": 1, 
                "name": "John",
                "username": "johndoexx",
                "password": "secret",
                "email": "johndoe@email.com"
            }]

### Remove an user [DELETE]
+ Response 204
